Models/Zaginiony.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace Zaginionki.Models
{
    public class Zaginiony
    {
        public int Id { get; set; }
        public string Imie { get; set; }
        public string Nazwisko { get; set; }
        [DataType(DataType.Date)]
        [Display(Name = "Data Zaginiecia")]
        public DateTime DataZaginiecia { get; set; }
        public string Wojewodztwo { get; set; }

        public string Opis { get; set; }
        public string Plec { get; set; }
        [DataType(DataType.ImageUrl)]
        public string Zdjecie { get; set; }
    }
}

Controllers/ZaginioniesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Zaginionki.Data;
using Zaginionki.Models;

namespace Zaginionki.Controllers
{
    public class ZaginioniesController : Controller
    {
        private readonly ZaginionkiContext _context;

        public ZaginioniesController(ZaginionkiContext context)
        {
            _context = context;
        }

        // GET: Zaginionies
        public async Task<IActionResult> Index(string pleec, string searchString)
        {
            IQueryable<string> genderQuery = from m in _context.Zaginiony
                                             orderby m.Plec
                                             select m.Plec;
            var zaginieni = from m in _context.Zaginiony select m;
            if (!String.IsNullOrEmpty(searchString))
            {
                zaginieni = zaginieni.Where(s => s.Wojewodztwo.Contains(searchString));
            }
            if (!String.IsNullOrEmpty(pleec))
            {
                zaginieni = zaginieni.Where(s => s.Plec.Contains(pleec));
            }
            var genderVM = new ZaginionyPlecViewModel
            {
                Plec = new SelectList(await genderQuery.Distinct().ToListAsync()),
                Zaginieni = await zaginieni.ToListAsync()
            };
            return View(genderVM);
        }

        // GET: Zaginionies/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var zaginiony = await _context.Zaginiony
                .FirstOrDefaultAsync(m => m.Id == id);
            if (zaginiony == null)
            {
                return NotFound();
            }

            return View(zaginiony);
        }

        // GET: Zaginionies/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Zaginionies/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Imie,Nazwisko,DataZaginiecia,Wojewodztwo,Opis,Zdjecie")] Zaginiony zaginiony)
        {
            if (ModelState.IsValid)
            {
                _context.Add(zaginiony);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(zaginiony);
        }

        // GET: Zaginionies/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var zaginiony = await _context.Zaginiony.FindAsync(id);
            if (zaginiony == null)
            {
                return NotFound();
            }
            return View(zaginiony);
        }

        // POST: Zaginionies/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Imie,Nazwisko,DataZaginiecia,Wojewodztwo,Opis,Zdjecie")] Zaginiony zaginiony)
        {
            if (id != zaginiony.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(zaginiony);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ZaginionyExists(zaginiony.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(zaginiony);
        }

        // GET: Zaginionies/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var zaginiony = await _context.Zaginiony
                .FirstOrDefaultAsync(m => m.Id == id);
            if (zaginiony == null)
            {
                return NotFound();
            }

            return View(zaginiony);
        }

        // POST: Zaginionies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var zaginiony = await _context.Zaginiony.FindAsync(id);
            _context.Zaginiony.Remove(zaginiony);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ZaginionyExists(int id)
        {
            return _context.Zaginiony.Any(e => e.Id == id);
        }
    }
}

Views/Zaginionies/Create.cshtml
@model Zaginionki.Models.Zaginiony

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Zaginiony</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Imie" class="control-label"></label>
                <input asp-for="Imie" class="form-control" />
                <span asp-validation-for="Imie" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nazwisko" class="control-label"></label>
                <input asp-for="Nazwisko" class="form-control" />
                <span asp-validation-for="Nazwisko" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataZaginiecia" class="control-label"></label>
                <input asp-for="DataZaginiecia" class="form-control" />
                <span asp-validation-for="DataZaginiecia" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Wojewodztwo" class="control-label"></label>
                <input asp-for="Wojewodztwo" class="form-control" />
                <span asp-validation-for="Wojewodztwo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Opis" class="control-label"></label>
                <input asp-for="Opis" class="form-control" />
                <span asp-validation-for="Opis" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Zdjecie" class="control-label"></label>
                <input asp-for="Zdjecie" class="form-control" />
                <span asp-validation-for="Zdjecie" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Zaginionies/Delete.cshtml
@model Zaginionki.Models.Zaginiony

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Zaginiony</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Imie)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Imie)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nazwisko)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nazwisko)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataZaginiecia)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataZaginiecia)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Wojewodztwo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Wojewodztwo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Opis)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Opis)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Zdjecie)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Zdjecie)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Zaginionies/Details.cshtml
@model Zaginionki.Models.Zaginiony

@{
    ViewData["Title"] = "Details";
    var imagePath = Model.Zdjecie;
}

<h1>Details</h1>

<div>
    <h4>Zaginiony</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Imie)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Imie)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nazwisko)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nazwisko)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataZaginiecia)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataZaginiecia)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Wojewodztwo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Wojewodztwo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Opis)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Opis)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Zdjecie)
        </dt>
        <dd class = "col-sm-10">
            <img src=@imagePath alt="Sample Image" width="300" />
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Zaginionies/Edit.cshtml
@model Zaginionki.Models.Zaginiony

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Zaginiony</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Imie" class="control-label"></label>
                <input asp-for="Imie" class="form-control" />
                <span asp-validation-for="Imie" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nazwisko" class="control-label"></label>
                <input asp-for="Nazwisko" class="form-control" />
                <span asp-validation-for="Nazwisko" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataZaginiecia" class="control-label"></label>
                <input asp-for="DataZaginiecia" class="form-control" />
                <span asp-validation-for="DataZaginiecia" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Wojewodztwo" class="control-label"></label>
                <input asp-for="Wojewodztwo" class="form-control" />
                <span asp-validation-for="Wojewodztwo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Opis" class="control-label"></label>
                <input asp-for="Opis" class="form-control" />
                <span asp-validation-for="Opis" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Plec" class="control-label"></label>
                <input asp-for="Plec" class="form-control" />
                <span asp-validation-for="Plec" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Zdjecie" class="control-label"></label>
                <input asp-for="Zdjecie" class="form-control" />
                <span asp-validation-for="Zdjecie" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Zaginionies/Index.cshtml
@model Zaginionki.Models.ZaginionyPlecViewModel

@{
    ViewData["Title"] = "Rejestr Osob Zaginionych";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<form asp-controller="Zaginionies" asp-action="Index">
    <p>
        Wojewodztwo:<input type="text" name="SearchString"/>
        <input type ="submit" value="Filter"/>
        <select asp-for="Plec" asp-items="Model.Plec">
            <option value="">All</option>
        </select>

    </p>
</form>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Zaginieni[0].Imie)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Zaginieni[0].Nazwisko)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Zaginieni[0].DataZaginiecia)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Zaginieni[0].Wojewodztwo)
            </th>
            @*<th>
                @Html.DisplayNameFor(model => model.Zaginieni[0].Opis)
            </th>*@
            <th>
                @Html.DisplayNameFor(model => model.Zaginieni[0].Plec)
            </th>
            @*<th>
                @Html.DisplayNameFor(model => model.Zaginieni[0].Zdjecie)
            </th>*@
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Zaginieni) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Imie)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nazwisko)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DataZaginiecia)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Wojewodztwo)
            </td>
            @*<td>
                @Html.DisplayFor(modelItem => item.Opis)
            </td>*@
            <td>
                @Html.DisplayFor(modelItem => item.Plec)
            </td>
            @*<td>
                @Html.DisplayFor(modelItem => item.Zdjecie)
            </td>*@

        <td>
            @if (User.Identity.IsAuthenticated && (User.IsInRole("Admin") ^ User.IsInRole("Verified")))
            {<a asp-action="Edit" asp-route-id="@item.Id">Edit</a>}|
            <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
            @if (User.Identity.IsAuthenticated && (User.IsInRole("Admin") ^ User.IsInRole("Verified")))
            {<a asp-action="Delete" asp-route-id="@item.Id">Delete</a>}
        </td>
        </tr>
}
    </tbody>
</table>